name: Upload Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Read commit index
        run: |
          GITHUB_COMMIT_INDEX=$(git rev-list --count HEAD)
          echo "GITHUB_COMMIT_INDEX=$GITHUB_COMMIT_INDEX" >> $GITHUB_ENV

      - name: Build (#${{ env.GITHUB_COMMIT_INDEX }})
        run: gradle build

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "#${{ env.GITHUB_COMMIT_INDEX }}"
          release_name: "Release #${{ env.GITHUB_COMMIT_INDEX }}"

      - name: Upload Release Asset
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/*.jar
          asset_name: null
          asset_content_type: null