name: Upload Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Read version
        run: |
          echo "PROJECT_VERSION=$(gradle -q printVersion)" >> $GITHUB_ENV
        id: android_version

      - name: Build (v${{ env.PROJECT_VERSION }})
        run: gradle build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/libs/*.jar"
          tag: "v${{ env.PROJECT_VERSION }}"
          body: "Release v${{ env.PROJECT_VERSION }}"